### ISSUE TITLE
Error in QiniuService

### ISSUE THREAD

**Issue by davidwessman** [qinmingyuan/qiniu_rails#1]
Hello.

I looked at your code as an example for ActiveStorage and noticed that you have a misspelling in your code:[`protocal` instead of `protocol`](https://github.com/qinmingyuan/qiniu_rails/blob/master/lib/active_storage/service/qiniu_service.rb#L19).

**Comment by qinmingyuan** [comment]
Thank you very much for your nice suggestion, I have done a commit to fix this issue~
